name: "Run tests"
# Currently does nothing

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: "Build project"
        run: echo "ok"

  test:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: "Run tests"
        run: echo "ok"
