name: "Run tests"
# Currently does nothing

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  ci:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - name: "Continuous integration checks"
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run build --if-present
          npm test
